apiVersion: apps/v1
kind: Deployment

#1 - metadata of this deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-01-15T12:51:26Z"
  generation: 1
  labels:
    app: home-cluster
  name: home-cluster
  namespace: default
  resourceVersion: "128438"
  uid: 76308e68-f7f5-4daf-baab-2e14b58b2e3e

#2 - specfication of this deployment
spec:
  #2a - defines the number of pod replicas created by this deployment
  replicas: 1

  #2b - defines the pods managed by this deployment - this deployment managed all pods with label app:home-cluster (selector.matchLabels == template.metadata.labels)
  selector:
    matchLabels:
      app: home-cluster

  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  progressDeadlineSeconds: 600

  #2c - defines the template for creating the pods created and managed by this deployment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: home-cluster
    spec:
      containers:
        - image: public.ecr.aws/w1c0p5q4/home-cluster:latest
          imagePullPolicy: Always
          name: home-cluster
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

#3 - status of the deployment
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2023-01-15T12:51:29Z"
      lastUpdateTime: "2023-01-15T12:51:29Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-01-15T12:51:26Z"
      lastUpdateTime: "2023-01-15T12:51:29Z"
      message: ReplicaSet "home-cluster-5f9bfc4586" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
